Do not fail on missing file during the backup

diff --git a/data/helpers.d/filesystem b/data/helpers.d/filesystem
--- a/data/helpers.d/filesystem
+++ b/data/helpers.d/filesystem
@@ -46,6 +46,7 @@ ynh_backup() {
     local SRC_PATH="$1"
     local DEST_PATH="${2:-}"
     local IS_BIG="${3:-0}"
+    local NEEDED="${4:-0}"
     BACKUP_CORE_ONLY=${BACKUP_CORE_ONLY:-0}
 
     # If backing up core only (used by ynh_backup_before_upgrade),
@@ -60,8 +61,14 @@ ynh_backup() {
     # ==============================================================================
     # Be sure the source path is not empty
     [[ -e "${SRC_PATH}" ]] || {
-        echo "Source path '${SRC_PATH}' does not exist" >&2
-        return 1
+        echo "!!! Source path '${SRC_PATH}' does not exist !!!" >&2
+        if [ $NEEDED -eq 1 ]
+        then
+                return 1
+        else
+                echo "The missing file will be replaced by a dummy one for the backup !!!" >&2
+                echo "This file is dummy... Please contact the maintainer of this app..." | tee "${SRC_PATH}" > /dev/null
+        fi
     }
 
     # Transform the source path as an absolute path
