Implement remaining comments

diff --git a/data/helpers.d/mysql b/data/helpers.d/mysql
--- a/data/helpers.d/mysql
+++ b/data/helpers.d/mysql
@@ -56,6 +56,9 @@ ynh_mysql_create_db() {
 
 # Drop a database
 #
+# If you intend to drop the database *and* the associated user,
+# consider using ynh_mysql_remove_db instead.
+#
 # usage: ynh_mysql_drop_db db
 # | arg: db - the database name to drop
 ynh_mysql_drop_db() {
@@ -93,15 +96,17 @@ ynh_mysql_drop_user() {
 
 # Create a database, an user and its password. Then store the password in the app's config
 #
-# Password of database will be stored in db_pwd's variable.
-# And store with the name mysqlpwd into the app config.
+# After executing this helper, the password of the created database will be available in $db_pwd
+# It will also be stored as "mysqlpwd" into the app settings.
 #
 # usage: ynh_mysql_setup_db user name
 # | arg: user - Owner of the database
 # | arg: name - Name of the database
 ynh_mysql_setup_db () {
+	local db_user="$1"
+	local db_name="$2"
 	db_pwd=$(ynh_string_random)	# Generate a random password
-	ynh_mysql_create_db "$2" "$1" "$db_pwd"	# Create the database
+	ynh_mysql_create_db "$db_name" "$db_user" "$db_pwd"	# Create the database
 	ynh_app_setting_set $app mysqlpwd $db_pwd	# Store the password in the app's config
 }
 
@@ -111,17 +116,21 @@ ynh_mysql_setup_db () {
 # | arg: user - Owner of the database
 # | arg: name - Name of the database
 ynh_mysql_remove_db () {
-	if mysqlshow -u root -p$(sudo cat $MYSQL_ROOT_PWD_FILE) | grep -q "^| $2"; then	# Check if the database exists
-		echo "Remove database $2" >&2
-		ynh_mysql_drop_db $2	# Remove the database
-		ynh_mysql_drop_user $1	# Remove the associated user to database
+	local db_user="$1"
+	local db_name="$2"
+	local mysql_root_password=$(sudo cat $MYSQL_ROOT_PWD_FILE)
+	if mysqlshow -u root -p$mysql_root_password | grep -q "^| $db_name"; then	# Check if the database exists
+		echo "Removing database $db_name" >&2
+		ynh_mysql_drop_db $db_name	# Remove the database	
 	else
-		echo "Database $2 not found" >&2
+		echo "Database $db_name not found" >&2
 	fi
+	
+	ynh_mysql_drop_user $db_user	# Remove the associated user to database
 }
 
-# Correct the name given in argument for mariadb
-# Avoid invalid characters in your database name
+# Sanitize a string intended to be the name of a database
+# (More specifically : replace - and . by _)
 #
 # Exemple: dbname=$(ynh_sanitize_dbid $app)
 #
@@ -129,6 +138,6 @@ ynh_mysql_remove_db () {
 # | arg: name - name to correct/sanitize
 # | ret: the corrected name
 ynh_sanitize_dbid () {
-	dbid=${1//[-.]/_}	# Mariadb doesn't support - and . in the name of databases. It will be replace by _
+	dbid=${1//[-.]/_}	# We should avoid having - and . in the name of databases. They are replaced by _
 	echo $dbid
 }
