Update psql helper

diff --git a/data/helpers.d/psql b/data/helpers.d/psql
--- a/data/helpers.d/psql
+++ b/data/helpers.d/psql
@@ -12,15 +12,15 @@ PSQL_ROOT_PWD_FILE=/etc/yunohost/psql
 # | arg: -p, --password - the user password
 # | arg: -d, --database - the database to connect to
 ynh_psql_connect_as() {
-    # Declare an array to define the options of this helper.
-    local legacy_args=upd
-    declare -Ar args_array=( [u]=user= [p]=password= [d]=database= )
-    local user
-    local password
-    local database
-    # Manage arguments with getopts
-    ynh_handle_getopts_args "$@"
-    database="${database:-}"
+	# Declare an array to define the options of this helper.
+	local legacy_args=upd
+	declare -Ar args_array=([u]=user= [p]=password= [d]=database=)
+	local user
+	local password
+	local database
+	# Manage arguments with getopts
+	ynh_handle_getopts_args "$@"
+	database="${database:-}"
 
 	sudo --login --user=postgres PGUSER="$user" PGPASSWORD="$password" psql "$database"
 }
@@ -30,18 +30,18 @@ ynh_psql_connect_as() {
 # usage: ynh_psql_execute_as_root --sql=sql [--database=database]
 # | arg: -s, --sql - the SQL command to execute
 # | arg: -d, --database - the database to connect to
-ynh_psql_execute_as_root () {
-    # Declare an array to define the options of this helper.
-    local legacy_args=sd
-    declare -Ar args_array=( [s]=sql= [d]=database= )
-    local sql
-    local database
-    # Manage arguments with getopts
-    ynh_handle_getopts_args "$@"
-    database="${database:-}"
+ynh_psql_execute_as_root() {
+	# Declare an array to define the options of this helper.
+	local legacy_args=sd
+	declare -Ar args_array=([s]=sql= [d]=database=)
+	local sql
+	local database
+	# Manage arguments with getopts
+	ynh_handle_getopts_args "$@"
+	database="${database:-}"
 
-    ynh_psql_connect_as --user="postgres" --password="$(sudo cat $PSQL_ROOT_PWD_FILE)" \
-        --database="$database" <<< "$sql"
+	ynh_psql_connect_as --user="postgres" --password="$(sudo cat $PSQL_ROOT_PWD_FILE)" \
+		--database="$database" <<<"$sql"
 }
 
 # Execute a command from a file as root user
@@ -50,17 +50,17 @@ ynh_psql_execute_as_root () {
 # | arg: -f, --file - the file containing SQL commands
 # | arg: -d, --database - the database to connect to
 ynh_psql_execute_file_as_root() {
-    # Declare an array to define the options of this helper.
-    local legacy_args=fd
-    declare -Ar args_array=( [f]=file= [d]=database= )
-    local file
-    local database
-    # Manage arguments with getopts
-    ynh_handle_getopts_args "$@"
-    database="${database:-}"
+	# Declare an array to define the options of this helper.
+	local legacy_args=fd
+	declare -Ar args_array=([f]=file= [d]=database=)
+	local file
+	local database
+	# Manage arguments with getopts
+	ynh_handle_getopts_args "$@"
+	database="${database:-}"
 
-    ynh_psql_connect_as --user="postgres" --password="$(sudo cat $PSQL_ROOT_PWD_FILE)" \
-        --database="$database" < "$file"
+	ynh_psql_connect_as --user="postgres" --password="$(sudo cat $PSQL_ROOT_PWD_FILE)" \
+		--database="$database" <"$file"
 }
 
 # Create a database and grant optionnaly privilegies to a user
@@ -72,10 +72,18 @@ ynh_psql_execute_file_as_root() {
 # | arg: user - the user to grant privilegies
 # | arg: pwd - the password to identify user by
 ynh_psql_create_db() {
-    local db=$1
+	local db=$1
 
-    ynh_psql_create_user "$user" "$pwd"
-	sudo --login --user=postgres createdb --owner="$user" "$db"
+    local sql="CREATE DATABASE ${db};"
+
+    # grant all privilegies to user
+	if [[ $# -gt 1 ]]; then
+		#ynh_psql_create_user "$user" "$pwd"
+		sql+=" GRANT ALL PRIVILEGES ON ${db} TO ${2}  WITH GRANT OPTION;"
+	fi
+
+	#sudo --login --user=postgres createdb --owner="$user" "$db"
+	ynh_psql_execute_as_root --sql="$sql"
 }
 
 # Drop a database
@@ -89,7 +97,7 @@ ynh_psql_create_db() {
 # | arg: db - the database name to drop
 ynh_psql_drop_db() {
 	local db=$1
-    sudo --login --user=postgres dropdb $db
+	sudo --login --user=postgres dropdb $db
 }
 
 # Dump a database
@@ -100,14 +108,14 @@ ynh_psql_drop_db() {
 # | arg: -d, --database - the database name to dump
 # | ret: the psqldump output
 ynh_psql_dump_db() {
-    # Declare an array to define the options of this helper.
-    local legacy_args=d
-    declare -Ar args_array=( [d]=database= )
-    local database
-    # Manage arguments with getopts
-    ynh_handle_getopts_args "$@"
+	# Declare an array to define the options of this helper.
+	local legacy_args=d
+	declare -Ar args_array=([d]=database=)
+	local database
+	# Manage arguments with getopts
+	ynh_handle_getopts_args "$@"
 
-    sudo --login --user=postgres pg_dump "$database"
+	sudo --login --user=postgres pg_dump "$database"
 }
 
 # Create a user
@@ -127,21 +135,48 @@ ynh_psql_create_user() {
 #
 # usage: ynh_psql_user_exists --user=user
 # | arg: -u, --user - the user for which to check existence
-ynh_psql_user_exists()
-{
-   # Declare an array to define the options of this helper.
-   local legacy_args=u
-   declare -Ar args_array=( [u]=user= )
-   local user
-   # Manage arguments with getopts
-   ynh_handle_getopts_args "$@"
+ynh_psql_user_exists() {
+	# Declare an array to define the options of this helper.
+	local legacy_args=u
+	declare -Ar args_array=([u]=user=)
+	local user
+	# Manage arguments with getopts
+	ynh_handle_getopts_args "$@"
 
-   if [[ -n $(sudo --login --user=postgres PGUSER="postgres" PGPASSWORD="$(sudo cat $PSQL_ROOT_PWD_FILE)" psql -tAc "SELECT rolname FROM pg_roles WHERE rolname='$user';") ]]
-   then
-      return 1
-   else
-      return 0
-   fi
+	if [[ -n $(sudo --login --user=postgres PGUSER="postgres" PGPASSWORD="$(sudo cat $PSQL_ROOT_PWD_FILE)" psql -tAc "SELECT rolname FROM pg_roles WHERE rolname='$user';") ]]; then
+		return 1
+	else
+		return 0
+	fi
+}
+
+# Check if a psql database exists
+#
+# usage: ynh_psql_database_exists --database=database
+# | arg: -d, --database - the database for which to check existence
+ynh_psql_database_exists() {
+	# Declare an array to define the options of this helper.
+	local legacy_args=u
+	declare -Ar args_array=([u]=database=)
+	local database
+	# Manage arguments with getopts
+	ynh_handle_getopts_args "$@"
+
+	if [[ -n $(sudo --login --user=postgres PGUSER="postgres" PGPASSWORD="$(sudo cat $PSQL_ROOT_PWD_FILE)" psql -tAc "SELECT datname FROM pg_database WHERE datname='$database';") ]]; then
+		return 1
+	else
+		return 0
+	fi
+}
+
+# Drop a user
+#
+# [internal]
+#
+# usage: ynh_psql_drop_user user
+# | arg: user - the user name to drop
+ynh_psql_drop_user() {
+	ynh_psql_execute_as_root --sql="DROP USER '${1}';"
 }
 
 # Create a database, an user and its password. Then store the password in the app's config
@@ -149,76 +184,54 @@ ynh_psql_user_exists()
 # After executing this helper, the password of the created database will be available in $db_pwd
 # It will also be stored as "psqlpwd" into the app settings.
 #
-# usage: ynh_psql_setup_db user name [pwd]
-# | arg: user - Owner of the database
-# | arg: name - Name of the database
-# | arg: pwd - Password of the database. If not given, a password will be generated
-ynh_psql_setup_db () {
-	local db_user="$1"
-	local db_name="$2"
-	local new_db_pwd=$(ynh_string_random)	# Generate a random password
-	# If $3 is not given, use new_db_pwd instead for db_pwd.
-	local db_pwd="${3:-$new_db_pwd}"
-	ynh_psql_create_db "$db_name" "$db_user" "$db_pwd"	# Create the database
-	ynh_app_setting_set "$app" psqlpwd "$db_pwd"	# Store the password in the app's config
+# usage: ynh_psql_setup_db --db_user=user --db_name=name [--db_pwd=pwd]
+# | arg: -u, --db_user - Owner of the database
+# | arg: -n, --db_name - Name of the database
+# | arg: -p, --db_pwd - Password of the database. If not given, a password will be generated
+ynh_psql_setup_db() {
+	# Declare an array to define the options of this helper.
+	local legacy_args=unp
+	declare -Ar args_array=([u]=db_user= [n]=db_name= [p]=db_pwd=)
+	local db_user
+	local db_name
+	db_pwd=""
+	# Manage arguments with getopts
+	ynh_handle_getopts_args "$@"
+
+	local new_db_pwd=$(ynh_string_random) # Generate a random password
+	# If $db_pwd is not given, use new_db_pwd instead for db_pwd
+	db_pwd="${db_pwd:-$new_db_pwd}"
+
+	ynh_psql_create_db "$db_name" "$db_user" "$db_pwd"           # Create the database
+	ynh_app_setting_set --app=$app --key=psqlpwd --value=$db_pwd # Store the password in the app's config
 }
 
-# Create a database and grant privilegies to a user
+# Remove a database if it exists, and the associated user
 #
-# usage: ynh_psql_create_db db [user [pwd]]
-# | arg: db - the database name to create
-# | arg: user - the user to grant privilegies
-# | arg: pwd  - the user password
-ynh_psql_create_db() {
-	local db="$1"
-	local user="$2"
-	local pwd="$3"
-	ynh_psql_create_user "$user" "$pwd"
-	sudo --login --user=postgres createdb --owner="$user" "$db"
-}
-
-# Drop a database
-#
-# usage: ynh_psql_drop_db db
-# | arg: db - the database name to drop
-# | arg: user - the user to drop
+# usage: ynh_psql_remove_db --db_user=user --db_name=name
+# | arg: -u, --db_user - Owner of the database
+# | arg: -n, --db_name - Name of the database
 ynh_psql_remove_db() {
-	local db="$1"
-	local user="$2"
-	sudo --login --user=postgres dropdb "$db"
-	ynh_psql_drop_user "$user"
-}
+	# Declare an array to define the options of this helper.
+	local legacy_args=un
+	declare -Ar args_array=([u]=db_user= [n]=db_name=)
+	local db_user
+	local db_name
+	# Manage arguments with getopts
+	ynh_handle_getopts_args "$@"
 
-# Dump a database
-#
-# example: ynh_psql_dump_db 'roundcube' > ./dump.sql
-#
-# usage: ynh_psql_dump_db db
-# | arg: db - the database name to dump
-# | ret: the psqldump output
-ynh_psql_dump_db() {
-	local db="$1"
-	sudo --login --user=postgres pg_dump "$db"
-}
+	local psql_root_password=$(sudo cat $PSQL_ROOT_PWD_FILE)
+	if ynh_psql_database_exists "$db_name"; then # Check if the database exists
+		echo "Removing database $db_name" >&2
+		ynh_psql_drop_db $db_name # Remove the database
+	else
+		echo "Database $db_name not found" >&2
+	fi
 
-
-# Create a user
-#
-# usage: ynh_psql_create_user user pwd [host]
-# | arg: user - the user name to create
-ynh_psql_create_user() {
-	local user="$1"
-	local pwd="$2"
-	sudo --login --user=postgres psql -c"CREATE USER $user WITH PASSWORD '$pwd'" postgres
-}
-
-# Drop a user
-#
-# usage: ynh_psql_drop_user user
-# | arg: user - the user name to drop
-ynh_psql_drop_user() {
-	local user="$1"
-	sudo --login --user=postgres dropuser "$user"
+	# Remove psql user if it exists
+	if $(ynh_psql_user_exists --user=$db_user); then
+		ynh_psql_drop_user $db_user
+	fi
 }
 
 # Create a master password and set up global settings
@@ -226,18 +239,15 @@ ynh_psql_drop_user() {
 #
 # usage: ynh_psql_test_if_first_run
 ynh_psql_test_if_first_run() {
-	if [ -f /etc/yunohost/psql ];
-	then
+	if [ -f /etc/yunohost/psql ]; then
 		echo "PostgreSQL is already installed, no need to create master password"
 	else
 		local pgsql="$(ynh_string_random)"
-		echo "$pgsql" > /etc/yunohost/psql
+		echo "$pgsql" >/etc/yunohost/psql
 
-		if [ -e /etc/postgresql/9.4/ ]
-		then
+		if [ -e /etc/postgresql/9.4/ ]; then
 			local pg_hba=/etc/postgresql/9.4/main/pg_hba.conf
-		elif [ -e /etc/postgresql/9.6/ ]
-		then
+		elif [ -e /etc/postgresql/9.6/ ]; then
 			local pg_hba=/etc/postgresql/9.6/main/pg_hba.conf
 		else
 			ynh_die "postgresql shoud be 9.4 or 9.6"
