Standardize tabulations

diff --git a/data/helpers.d/utils b/data/helpers.d/utils
--- a/data/helpers.d/utils
+++ b/data/helpers.d/utils
@@ -17,22 +17,22 @@
 # It prints a warning to inform that the script was failed, and execute the ynh_clean_setup function if used in the app script
 #
 ynh_exit_properly () {
-	local exit_code=$?
-	if [ "$exit_code" -eq 0 ]; then
-			exit 0	# Exit without error if the script ended correctly
-	fi
+    local exit_code=$?
+    if [ "$exit_code" -eq 0 ]; then
+        exit 0	# Exit without error if the script ended correctly
+    fi
 
-	trap '' EXIT	# Ignore new exit signals
-	set +eu	# Do not exit anymore if a command fail or if a variable is empty
+    trap '' EXIT	# Ignore new exit signals
+    set +eu	# Do not exit anymore if a command fail or if a variable is empty
 
-	# Small tempo to avoid the next message being mixed up with other DEBUG messages
-	sleep 0.5
+    # Small tempo to avoid the next message being mixed up with other DEBUG messages
+    sleep 0.5
 
-	if type -t ynh_clean_setup > /dev/null; then	# Check if the function exist in the app script.
-		ynh_clean_setup	# Call the function to do specific cleaning for the app.
-	fi
+    if type -t ynh_clean_setup > /dev/null; then	# Check if the function exist in the app script.
+        ynh_clean_setup	# Call the function to do specific cleaning for the app.
+    fi
 
-	ynh_die	# Exit with error status
+    ynh_die	# Exit with error status
 }
 
 # Exits if an error occurs during the execution of the script.
@@ -46,8 +46,8 @@ ynh_exit_properly () {
 #
 # Requires YunoHost version 2.6.4 or higher.
 ynh_abort_if_errors () {
-	set -eu	# Exit if a command fail, and if a variable is used unset.
-	trap ynh_exit_properly EXIT	# Capturing exit signals on shell script
+    set -eu	# Exit if a command fail, and if a variable is used unset.
+    trap ynh_exit_properly EXIT	# Capturing exit signals on shell script
 }
 
 # Download, check integrity, uncompress and patch the source from app.src
@@ -256,13 +256,13 @@ ynh_local_curl () {
 # | arg: some_template - Template file to be rendered
 # | arg: output_path   - The path where the output will be redirected to
 ynh_render_template() {
-   local template_path=$1
-   local output_path=$2
-   mkdir -p "$(dirname $output_path)"
-   # Taken from https://stackoverflow.com/a/35009576
-   python2.7 -c 'import os, sys, jinja2; sys.stdout.write(
+    local template_path=$1
+    local output_path=$2
+    mkdir -p "$(dirname $output_path)"
+    # Taken from https://stackoverflow.com/a/35009576
+    python2.7 -c 'import os, sys, jinja2; sys.stdout.write(
                     jinja2.Template(sys.stdin.read()
-                 ).render(os.environ));' < $template_path > $output_path
+                    ).render(os.environ));' < $template_path > $output_path
 }
 
 # Fetch the Debian release codename
@@ -272,7 +272,7 @@ ynh_render_template() {
 #
 # Requires YunoHost version 2.7.12 or higher.
 ynh_get_debian_release () {
-	echo $(lsb_release --codename --short)
+    echo $(lsb_release --codename --short)
 }
 
 # Create a directory under /tmp
@@ -376,20 +376,20 @@ ynh_get_plain_key() {
 #
 # Requires YunoHost version 3.5.0 or higher.
 ynh_read_manifest () {
-	# Declare an array to define the options of this helper.
-        local legacy_args=mk
-        local -A args_array=( [m]=manifest= [k]=manifest_key= )
-        local manifest
-        local manifest_key
-	# Manage arguments with getopts
-	ynh_handle_getopts_args "$@"
+    # Declare an array to define the options of this helper.
+    local legacy_args=mk
+    local -A args_array=( [m]=manifest= [k]=manifest_key= )
+    local manifest
+    local manifest_key
+    # Manage arguments with getopts
+    ynh_handle_getopts_args "$@"
 
-	if [ ! -e "$manifest" ]; then
-		# If the manifest isn't found, try the common place for backup and restore script.
-		manifest="../settings/manifest.json"
-	fi
+    if [ ! -e "$manifest" ]; then
+        # If the manifest isn't found, try the common place for backup and restore script.
+        manifest="../settings/manifest.json"
+    fi
 
-	jq ".$manifest_key" "$manifest" --raw-output
+    jq ".$manifest_key" "$manifest" --raw-output
 }
 
 # Read the upstream version from the manifest
@@ -458,32 +458,32 @@ ynh_app_package_version () {
 #
 # Requires YunoHost version 3.5.0 or higher.
 ynh_check_app_version_changed () {
-  local force_upgrade=${YNH_FORCE_UPGRADE:-0}
-  local package_check=${PACKAGE_CHECK_EXEC:-0}
+    local force_upgrade=${YNH_FORCE_UPGRADE:-0}
+    local package_check=${PACKAGE_CHECK_EXEC:-0}
 
-  # By default, upstream app version has changed
-  local return_value="UPGRADE_APP"
+    # By default, upstream app version has changed
+    local return_value="UPGRADE_APP"
 
-  local current_version=$(ynh_read_manifest --manifest="/etc/yunohost/apps/$YNH_APP_INSTANCE_NAME/manifest.json" --manifest_key="version" || echo 1.0)
-  local current_upstream_version="$(ynh_app_upstream_version --manifest="/etc/yunohost/apps/$YNH_APP_INSTANCE_NAME/manifest.json")"
-  local update_version=$(ynh_read_manifest --manifest="../manifest.json" --manifest_key="version" || echo 1.0)
-  local update_upstream_version="$(ynh_app_upstream_version)"
+    local current_version=$(ynh_read_manifest --manifest="/etc/yunohost/apps/$YNH_APP_INSTANCE_NAME/manifest.json" --manifest_key="version" || echo 1.0)
+    local current_upstream_version="$(ynh_app_upstream_version --manifest="/etc/yunohost/apps/$YNH_APP_INSTANCE_NAME/manifest.json")"
+    local update_version=$(ynh_read_manifest --manifest="../manifest.json" --manifest_key="version" || echo 1.0)
+    local update_upstream_version="$(ynh_app_upstream_version)"
 
-  if [ "$current_version" == "$update_version" ] ; then
-      # Complete versions are the same
-      if [ "$force_upgrade" != "0" ]
-      then
-        ynh_print_info --message="Upgrade forced by YNH_FORCE_UPGRADE."
-        unset YNH_FORCE_UPGRADE
-      elif [ "$package_check" != "0" ]
-      then
-        ynh_print_info --message="Upgrade forced for package check."
-      else
-        ynh_die "Up-to-date, nothing to do" 0
-      fi
-  elif [ "$current_upstream_version" == "$update_upstream_version" ] ; then
-    # Upstream versions are the same, only YunoHost package versions differ
-    return_value="UPGRADE_PACKAGE"
-  fi
-  echo $return_value
+    if [ "$current_version" == "$update_version" ] ; then
+        # Complete versions are the same
+        if [ "$force_upgrade" != "0" ]
+        then
+            ynh_print_info --message="Upgrade forced by YNH_FORCE_UPGRADE."
+            unset YNH_FORCE_UPGRADE
+        elif [ "$package_check" != "0" ]
+        then
+            ynh_print_info --message="Upgrade forced for package check."
+        else
+            ynh_die "Up-to-date, nothing to do" 0
+        fi
+    elif [ "$current_upstream_version" == "$update_upstream_version" ] ; then
+        # Upstream versions are the same, only YunoHost package versions differ
+        return_value="UPGRADE_PACKAGE"
+    fi
+    echo $return_value
 }
