Get rid of /etc/yunohost/mysql

diff --git a/data/hooks/conf_regen/34-mysql b/data/hooks/conf_regen/34-mysql
--- a/data/hooks/conf_regen/34-mysql
+++ b/data/hooks/conf_regen/34-mysql
@@ -1,7 +1,6 @@
 #!/bin/bash
 
 set -e
-MYSQL_PKG="$(dpkg --list | sed -ne 's/^ii  \(mariadb-server-[[:digit:].]\+\) .*$/\1/p')"
 . /usr/share/yunohost/helpers
 
 do_pre_regen() {
@@ -27,17 +26,30 @@ do_post_regen() {
 
       sleep 5
 
-      echo "" | mysql && echo "Can't connect to mysql using unix_socket auth ... something went wrong during initial configuration of mysql !?"
+      echo "" | mysql && echo "Can't connect to mysql using unix_socket auth ... something went wrong during initial configuration of mysql !?" >&2
   fi
 
-  if [ ! -e /etc/yunohost/mysql ]
-  then
-      # Dummy password that's not actually used nor meaningful ...
-      # (because mysql is supposed to be configured to use unix_socket on new setups)
-      # but keeping it for legacy
-      # until we merge https://github.com/YunoHost/yunohost/pull/912 ...
-      ynh_string_random 10 > /etc/yunohost/mysql
-      chmod 400 /etc/yunohost/mysql
+  # Legacy code to get rid of /etc/yunohost/mysql ...
+  # Nowadays, we can simply run mysql while being run as root of unix_socket/auth_socket is enabled...
+  if [ -f /etc/yunohost/mysql ]; then
+
+      # This is a trick to check if we're able to use mysql without password
+      # Expect instances installed in stretch to already have unix_socket
+      #configured, but not old instances from the jessie/wheezy era
+      if ! echo "" | mysql
+      then
+          password="$(cat /etc/yunohost/mysql)"
+          # Enable plugin unix_socket for root on localhost
+          mysql -u root -p"$password" <<< "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED WITH unix_socket WITH GRANT OPTION;"
+      fi
+
+      # If now we're able to login without password, drop the mysql password
+      if echo "" | mysql
+      then
+          rm /etc/yunohost/mysql
+      else
+          echo "Can't connect to mysql using unix_socket auth ... something went wrong while trying to get rid of mysql password !?" >&2
+      fi
   fi
 
   # mysql is supposed to be an alias to mariadb... but in some weird case is not
