Rewrite the fail2ban helper for reaction

diff --git a/helpers/helpers.v2.1.d/fail2ban b/helpers/helpers.v2.1.d/fail2ban
--- a/helpers/helpers.v2.1.d/fail2ban
+++ b/helpers/helpers.v2.1.d/fail2ban
@@ -18,57 +18,53 @@
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 
-# Create a dedicated fail2ban config (jail and filter conf files)
+# Create a dedicated reaction config (conf file with stream and filter)
 #
 # usage: ynh_config_add_fail2ban --logpath=log_file --failregex=filter
-# | arg: --logpath=   - Log file to be checked by fail2ban
-# | arg: --failregex= - Failregex to be looked for by fail2ban
+# | arg: --logpath=   - Log file to be checked by reaction
+# | arg: --failregex= - Failregex to be looked for by reaction
 #
 # If --logpath / --failregex are provided, the helper will generate the appropriate conf using these.
 #
-# Otherwise, it will assume that the app provided templates, namely
-# `../conf/f2b_jail.conf` and `../conf/f2b_filter.conf`
+# Otherwise, it will assume that the app provides a template named `../conf/reaction_filter.jsonnet`
 #
-# They will typically look like (for example here for synapse):
+# It will typically look like (for example here for a php app):
 #
-# ```toml
-# f2b_jail.conf:
-#     [__APP__]
-#     enabled = true
-#     port = http,https
-#     filter = __APP__
-#     logpath = /var/log/__APP__/logfile.log
-#     maxretry = 5
-# ```
-#
-# ```toml
-# f2b_filter.conf:
-#     [INCLUDES]
-#     before = common.conf
-#     [Definition]
-#
-#     # Part of regex definition (just used to make more easy to make the global regex)
-#     __synapse_start_line = .? \- synapse\..+ \-
-#
-#    # Regex definition.
-#    failregex = ^%(__synapse_start_line)s INFO \- POST\-(\d+)\- <HOST> \- \d+ \- Received request\: POST /_matrix/client/r0/login\??<SKIPLINES>%(__synapse_start_line)s INFO \- POST\-\1\- Got login request with identifier: \{u'type': u'm.id.user', u'user'\: u'(.+?)'\}, medium\: None, address: None, user\: u'\5'<SKIPLINES>%(__synapse_start_line)s WARNING \- \- (Attempted to login as @\5\:.+ but they do not exist|Failed password login for user @\5\:.+)$
-#
-#     ignoreregex =
+# ```jsonnet
+# local ban = import '_ban.jsonnet';
+# {
+#   streams: {
+#     '__APP__': {
+#       cmd: ['tail', '-Fn0', '/var/log/nginx/__DOMAIN__-error.log'],
+#       filters: {
+#         'authfail': {
+#           regex: [ @'auth\.php.*failed login attempt.*from IP <HOST>$' ]
+#           retry: 5,
+#           retryperiod: '5h',
+#           actions: ban('1h'),
+#         },
+#       },
+#     },
+#   },
+# }
 # ```
 #
 # ##### Regarding the the `failregex` option
 #
 # regex to match the password failure messages in the logfile. The host must be
-# matched by a group named "`host`". The tag "`<HOST>`" can be used for standard
-# IP/hostname matching and is only an alias for `(?:::f{4,6}:)?(?P<host>[\w\-.^_]+)`
+# matched by a group named "`host`". The pattern "`<HOST>`" can be used for standard
+# IP matching and will match both IPv4 and IPv6 addresses.
 #
-# You can find some more explainations about how to make a regex on [the official fail2ban documentation](https://www.fail2ban.org/wiki/index.php/MANUAL_0_8#Filters).
+# You can find some more explainations about how to make a regex on [the official reaction documentation](https://reaction.ppom.me/get-started/tutorial-en/#retrieving-logs).
 #
 # To validate your regex you can test with this command:
 #
 # ```bash
-# fail2ban-regex /var/log/YOUR_LOG_FILE_PATH /etc/fail2ban/filter.d/YOUR_APP.conf
+# cat /var/log/YOUR_LOG_FILE_PATH | reaction test-regex -c /etc/reaction/ 'YOUR_REGEX'
 # ```
+
+conf_path="/etc/reaction/app-$app.jsonnet"
+
 ynh_config_add_fail2ban() {
     # ============ Argument parsing =============
     local -A args_array=([l]=logpath= [r]=failregex=)
@@ -77,62 +73,59 @@ ynh_config_add_fail2ban() {
     ynh_handle_getopts_args "$@"
     # ===========================================
 
+    # Test that reaction is running
+    systemctl is-active --quiet reaction.service && local reaction_running=1
+
     # If failregex is provided, Build a config file on-the-fly using $logpath and $failregex
-    if [[ -n "${failregex:-}" ]]; then
+    if test -n "${failregex:-}"
+    then
         test -n "$logpath" || ynh_die "ynh_config_add_fail2ban expects a logfile path as first argument and received nothing."
 
-        echo "
-[__APP__]
-enabled = true
-port = http,https
-filter = __APP__
-logpath = __LOGPATH__
-maxretry = 5
-" > "$YNH_APP_BASEDIR/conf/f2b_jail.conf"
+        local streamname="$(tr '.' '_' <<< "$logpath")"
 
         echo "
-[INCLUDES]
-before = common.conf
-[Definition]
-failregex = __FAILREGEX__
-ignoreregex =
-" > "$YNH_APP_BASEDIR/conf/f2b_filter.conf"
+local ban = import '_ban.jsonnet';
+{
+  streams: {
+    '$streamname': {
+      cmd: ['tail', '-Fn0', '$logpath'],
+      filters: {
+        '$app': {
+          regex: [ @'$failregex' ],
+          retry: 5,
+          retryperiod: '5h',
+          actions: ban('1h'),
+        },
+      },
+    },
+  },
+}
+" > "$YNH_APP_BASEDIR/conf/reaction_filter.jsonnet"
     fi
 
-    ynh_config_add --template="f2b_jail.conf" --destination="/etc/fail2ban/jail.d/$app.conf"
-    ynh_config_add --template="f2b_filter.conf" --destination="/etc/fail2ban/filter.d/$app.conf"
+    ynh_config_add --template="reaction_filter.jsonnet" --destination="$conf_path"
 
-    # Create the folder and logfile if they doesn't exist,
-    # as fail2ban require an existing logfile before configuration
-    local logdir=$(dirname "$logpath")
-    if [ ! -d "$logdir" ]; then
-        mkdir -p "$logdir"
-        # Make sure log folder's permissions are correct
-        chown "$app:$app" "$logdir"
-        chmod u=rwX,g=rX,o= "$logdir"
-    fi
+    ynh_systemctl --service=reaction --action=restart --wait_until="(Started|Restarted) reaction.service" --log_path=systemd
 
-    if [ ! -f "$logpath" ]; then
-        touch "$logpath"
-        # Make sure log file's permissions are correct
-        chown "$app:$app" "$logpath"
-        chmod u=rwX,g=rX,o= "$logpath"
-    fi
+    # Test if reaction failed (and that it was running in the first place)
+    systemctl --failed | grep -q reaction.service
+    if test $? -eq 0 && test -n "$reaction_running"
+    then
+        # Log the error
+        local reaction_error="$(journalctl --no-hostname --unit=reaction.service --lines=50 | grep "ERROR.*$app.*")"
+        ynh_print_warn "reaction failed to load the configuration for $app"
+        ynh_print_warn "${reaction_error#*WARNING}"
 
-    ynh_systemctl --service=fail2ban --action=reload --wait_until="(Started|Reloaded) fail2ban.service" --log_path=systemd
-
-    local fail2ban_error="$(journalctl --no-hostname --unit=fail2ban | tail --lines=50 | grep "WARNING.*$app.*")"
-    if [[ -n "$fail2ban_error" ]]; then
-        ynh_print_warn "Fail2ban failed to load the jail for $app"
-        ynh_print_warn "${fail2ban_error#*WARNING}"
+        # Suffix the app's reaction conf and restart reaction
+        mv "$conf_path" "$conf_path.failed"
+        ynh_systemctl --service=reaction --action=restart --wait_until="(Started|Restarted) reaction.service" --log_path=systemd
     fi
 }
 
-# Remove the dedicated fail2ban config (jail and filter conf files)
+# Remove the dedicated reaction config (jail and filter conf files)
 #
-# usage: ynh_config_remove_fail2ban
+# usage: ynh_config_remove_reaction
 ynh_config_remove_fail2ban() {
-    ynh_safe_rm "/etc/fail2ban/jail.d/$app.conf"
-    ynh_safe_rm "/etc/fail2ban/filter.d/$app.conf"
-    ynh_systemctl --service=fail2ban --action=reload
+    ynh_safe_rm "$conf_path"
+    ynh_systemctl --service=reaction --action=restart
 }
