use mise to ease helpers

diff --git a/helpers/helpers.v2.1.d/go b/helpers/helpers.v2.1.d/go
--- a/helpers/helpers.v2.1.d/go
+++ b/helpers/helpers.v2.1.d/go
@@ -18,13 +18,11 @@
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 
-readonly GOENV_ROOT="/opt/goenv"
-export GOENV_ROOT
-
+# [internal]
 _ynh_load_go_in_path_and_other_tweaks() {
 
     # Get the absolute path of this version of go
-    go_dir="$GOENV_ROOT/versions/$go_version/bin"
+    go_dir=$(MISE_DATA_DIR=$MISE_DATA_DIR MISE_CACHE_DIR=$MISE_CACHE_DIR "$MISE_BIN_DIR/mise" bin-paths "go@$go_version")
 
     if [ ! -e "$go_dir" ]; then
         echo "Skipping loading go, because it doesn't seem to be provisioned yet. This is likely to happen during restore and other specific contexts."
@@ -40,13 +38,10 @@ _ynh_load_go_in_path_and_other_tweaks() {
     export PATH
 
     # This is in full lowercase such that it gets replaced in templates
+    # shellcheck disable=SC2034
     path_with_go="$PATH"
+    # shellcheck disable=SC2034
     PATH_with_go="$PATH"
-
-    # Sets the local application-specific go version
-    pushd "${install_dir}"
-        "$GOENV_ROOT/bin/goenv" local "$go_version"
-    popd
 }
 
 # Auto-load Go path tweaks if this app uses the Go resource in the manifest
@@ -54,7 +49,7 @@ if [ -n "${go_version:-}" ] && (cat "$YNH_APP_BASEDIR/manifest.toml" | toml_to_j
     _ynh_load_go_in_path_and_other_tweaks
 fi
 
-# Install a specific version of Go using goenv
+# Install a specific version of Go, using mise
 #
 # The installed version is defined by `$go_version` which should be defined as global prior to calling this helper
 #
@@ -63,41 +58,36 @@ fi
 # The helper adds the appropriate, specific version of go to the `$PATH` variable (which
 # is preserved when calling `ynh_exec_as_app`). Also defines:
 #
-# - `$path_with_go` (the value of the modified `$PATH`, but you dont really need it?)
-# - `$go_dir` (the directory containing the specific go version)
+# - `$path_with_go` to be used in the systemd config (`Environment="PATH=__PATH_WITH_GO__"`)
+# - `$go_dir`, the directory containing the specific version of go, which may be used in the systemd config too (e.g. `ExecStart=__go_DIR__/node foo bar`)
 ynh_go_install() {
 
     [[ -n "${go_version:-}" ]] || ynh_die "\$go_version should be defined prior to calling ynh_go_install"
 
-    _ynh_git_clone "https://github.com/syndbg/goenv" "$GOENV_ROOT"
-    _ynh_git_clone "https://github.com/momo-lab/xxenv-latest" "$GOENV_ROOT/plugins/xxenv-latest"
-
-    # Enable caching
-    mkdir -p "${GOENV_ROOT}/cache"
-    # Create shims directory if needed
-    mkdir -p "${GOENV_ROOT}/shims"
+    ynh_mise_install
 
     # Install the requested version of Go
-    local final_go_version=$(PATH=$GOENV_ROOT/bin:$PATH "$GOENV_ROOT/plugins/xxenv-latest/bin/goenv-latest" --print "$go_version")
-    go_version=$final_go_version
-    ynh_app_setting_set --app="$app" --key="go_version" --value="$go_version"
+    local final_go_version=$("${MISE_BIN_DIR}"/mise ls-remote go@"$go_version" --json | jq -r '.[].version' | tail -n1 )
+    go_version=${final_go_version:-$go_version}
+    ynh_app_setting_set --key=go_version --value="$go_version"
 
-    ynh_print_info "Installing Go $go_version"
-    $GOENV_ROOT/bin/goenv install --quiet --skip-existing "$go_version" 2>&1
-
-    # Cleanup Go versions
-    _ynh_go_cleanup
+    # Installing precompiled go from the $install_dir so the created mise.toml will be at the right place
+    pushd "$install_dir" || ynh_die
+        ynh_hide_warnings env MISE_DATA_DIR="$MISE_DATA_DIR" MISE_CACHE_DIR="$MISE_CACHE_DIR" "$MISE_BIN_DIR"/mise use go@"$go_version"
+    popd || ynh_die
 
     _ynh_load_go_in_path_and_other_tweaks
 }
 
 # Remove the version of Go used by the app.
 #
-# This helper will also cleanup Go versions
+# This helper will also cleanup unused Go versions
 #
 # usage: ynh_go_remove
 ynh_go_remove() {
-    # Remove the line for this app
+
+    [[ -n "${go_version:-}" ]] || ynh_die "\$go_version should be defined prior to calling ynh_go_remove"
+
     ynh_app_setting_delete --key="go_version"
 
     # Cleanup Go versions
@@ -110,25 +100,31 @@ ynh_go_remove() {
 #
 # This helper will check what Go version are no more required,
 # and uninstall them
-# If no app uses Go, goenv will be also removed.
 #
 # usage: _ynh_go_cleanup
 _ynh_go_cleanup() {
 
-    # Remove no more needed Go versions
-    local installed_go_versions=$($GOENV_ROOT/bin/goenv versions --bare --skip-aliases | grep -Ev '/')
+    # This helper will check what Go version are no more required,
+    # and uninstall them
+    local installed_go_versions=$(MISE_DATA_DIR=$MISE_DATA_DIR MISE_CACHE_DIR=$MISE_CACHE_DIR "${MISE_BIN_DIR}/mise" ls go --json | jq -r '.[].version')
     for installed_go_version in $installed_go_versions; do
-        if ! grep -qE "^go_version: '?$installed_go_version'?" /etc/yunohost/apps/*/settings.yml; then
-            # ynh_print_info "Removing Go-$installed_go_version"
-            $GOENV_ROOT/bin/goenv uninstall --force "$installed_go_version"
+        if [[ -n "$installed_go_version" ]] && ! grep -qE "^go_version: '?$installed_go_version'?" /etc/yunohost/apps/*/settings.yml; then
+            ynh_print_info "Removing go@$installed_go_version"
+            ynh_hide_warnings "$MISE_BIN_DIR/mise" unuse go@"$installed_go_version"
+            ynh_hide_warnings "$MISE_BIN_DIR/mise" uninstall go@"$installed_go_version"
         fi
     done
 
-    # If no app uses Go anymore
-    if ! grep -q "^go_version:" /etc/yunohost/apps/*/settings.yml; then
-        # Remove goenv environment configuration
-        # ynh_print_info "Removing goenv"
-        ynh_safe_rm "$GOENV_ROOT"
-        ynh_safe_rm "/etc/profile.d/goenv.sh"
+    # LEGACY but still here for transition
+    export GOENV_ROOT="/opt/goenv"
+    if -e "$GOENV_ROOT"; then
+    
+        # If no app uses Go anymore
+        if ! grep -q "^go_version:" /etc/yunohost/apps/*/settings.yml; then
+            # Remove goenv environment configuration
+            # ynh_print_info "Removing goenv"
+            ynh_safe_rm "$GOENV_ROOT"
+            ynh_safe_rm "/etc/profile.d/goenv.sh"
+        fi
     fi
 }
diff --git a/helpers/helpers.v2.1.d/nodejs b/helpers/helpers.v2.1.d/nodejs
--- a/helpers/helpers.v2.1.d/nodejs
+++ b/helpers/helpers.v2.1.d/nodejs
@@ -18,14 +18,13 @@
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 
-readonly N_PREFIX="/opt/node_n"
-export N_PREFIX
+export MISE_NODE_COREPACK=true
 
 # [internal]
 _ynh_load_nodejs_in_path_and_other_tweaks() {
 
     # Get the absolute path of this version of node
-    nodejs_dir="$N_PREFIX/n/versions/node/$nodejs_version/bin"
+    nodejs_dir=$(MISE_DATA_DIR=$MISE_DATA_DIR MISE_CACHE_DIR=$MISE_CACHE_DIR "$MISE_BIN_DIR/mise" bin-paths "nodejs@$nodejs_version")
 
     if [ ! -e "$nodejs_dir" ]; then
         echo "Skipping loading nodejs, because it doesn't seem to be provisioned yet. This is likely to happen during restore and other specific contexts."
@@ -56,14 +55,11 @@ if [ -n "${nodejs_version:-}" ] && (cat "$YNH_APP_BASEDIR/manifest.toml" | toml_
     _ynh_load_nodejs_in_path_and_other_tweaks
 fi
 
-# Install a specific version of nodejs, using 'n'
+# Install a specific version of nodejs, using mise
 #
 # The installed version is defined by `$nodejs_version` which should be defined as global prior to calling this helper
 #
 # usage: ynh_nodejs_install
-#
-# `n` (Node version management) uses the `PATH` variable to store the path of the version of node it is going to use.
-# That's how it changes the version
 #
 # The helper adds the appropriate, specific version of nodejs to the `$PATH` variable (which
 # is preserved when calling ynh_exec_as_app). Also defines:
@@ -71,56 +67,60 @@ fi
 # - `$path_with_nodejs` to be used in the systemd config (`Environment="PATH=__PATH_WITH_NODEJS__"`)
 # - `$nodejs_dir`, the directory containing the specific version of nodejs, which may be used in the systemd config too (e.g. `ExecStart=__NODEJS_DIR__/node foo bar`)
 ynh_nodejs_install() {
-    # Use n, https://github.com/tj/n to manage the nodejs versions
 
     [[ -n "${nodejs_version:-}" ]] || ynh_die "\$nodejs_version should be defined prior to calling ynh_nodejs_install"
 
-    # Create $N_PREFIX
-    mkdir --parents "$N_PREFIX"
+    ynh_mise_install
 
     # Install the requested version of nodejs
-    if [[ $YNH_ARCH == "arm64" ]]; then
-        "$YNH_HELPERS_DIR/vendor/n/n" install "$nodejs_version" --arch=arm64
-    else
-        "$YNH_HELPERS_DIR/vendor/n/n" install "$nodejs_version"
-    fi
+    local final_nodejs_version=$("${MISE_BIN_DIR}"/mise ls-remote nodejs@"$nodejs_version" --json | jq -r '.[].version' | tail -n1 )
+    nodejs_version=${final_nodejs_version:-$nodejs_version}
+    ynh_app_setting_set --key=nodejs_version --value="$nodejs_version"
 
-    # Find the last "real" version for this major version of node.
-    final_nodejs_version=$(find "$N_PREFIX/n/versions/node/$nodejs_version"* -maxdepth 0 | sort --version-sort | tail --lines=1)
-    final_nodejs_version=$(basename "$final_nodejs_version")
-
-    # Store nodejs_version into the config of this app
-    nodejs_version="$final_nodejs_version"
-    ynh_app_setting_set --key=nodejs_version --value="$final_nodejs_version"
+    # Installing precompiled nodejs from the $install_dir so the created mise.toml will be at the right place
+    pushd "$install_dir" || ynh_die
+        # The path has to be set for npm to now where to find node
+        PATH="$MISE_DATA_DIR/installs/node/$nodejs_version/bin:$PATH"
+        ynh_hide_warnings env MISE_DATA_DIR="$MISE_DATA_DIR" MISE_CACHE_DIR="$MISE_CACHE_DIR" "$MISE_BIN_DIR"/mise use nodejs@"$nodejs_version"
+    popd || ynh_die
 
     _ynh_load_nodejs_in_path_and_other_tweaks
 }
 
 # Remove the version of node used by the app.
 #
+# This helper will also cleanup unused nodejs versions
+#
 # usage: ynh_nodejs_remove
-#
-# This helper will check if another app uses the same version of node.
-#
-# - If not, this version of node will be removed.
-# - If no other app uses node, n will be also removed.
 ynh_nodejs_remove() {
+    _ynh_nodejs_cleanup
+}
 
+_ynh_nodejs_cleanup() {
     [[ -n "${nodejs_version:-}" ]] || ynh_die "\$nodejs_version should be defined prior to calling ynh_nodejs_remove"
 
-    ynh_app_setting_delete --key=nodejs_version
+    ynh_app_setting_delete --key="nodejs_version"
 
-    # Garbage-collect unused versions
-    local installed_versions="$(N_PREFIX=/opt/node_n "$YNH_HELPERS_DIR/vendor/n/n" ls | awk -F/ '{print $2}')"
-    for version in $installed_versions; do
-        if ! grep -qE "^nodejs_version: '?$version'?" /etc/yunohost/apps/*/settings.yml; then
-            "$YNH_HELPERS_DIR/vendor/n/n" rm "$version"
+    # Remove no more needed versions of nodejs used by the app.
+    # This helper will check what nodejs version are no more required,
+    # and uninstall them
+    local installed_nodejs_versions=$(MISE_DATA_DIR=$MISE_DATA_DIR MISE_CACHE_DIR=$MISE_CACHE_DIR "${MISE_BIN_DIR}/mise" ls nodejs --json | jq -r '.[].version')
+    for installed_nodejs_version in $installed_nodejs_versions; do
+        if [[ -n "$installed_nodejs_version" ]] && ! grep -qE "^nodejs_version: '?$installed_nodejs_version'?" /etc/yunohost/apps/*/settings.yml; then
+            ynh_print_info "Removing nodejs@$installed_nodejs_version"
+            ynh_hide_warnings "$MISE_BIN_DIR/mise" unuse nodejs@"$installed_nodejs_version"
+            ynh_hide_warnings "$MISE_BIN_DIR/mise" uninstall nodejs@"$installed_nodejs_version"
         fi
     done
 
-    # If no other app uses n, remove n
-    if ! grep -q "^nodejs_version:" /etc/yunohost/apps/*/settings.yml; then
-        ynh_safe_rm "$N_PREFIX"
-        sed --in-place "/N_PREFIX/d" /root/.bashrc
+    # LEGACY but still here for transition
+    export GOENV_ROOT="/opt/goenv"
+    if -e "$GOENV_ROOT"; then
+    
+        # If no other app uses n, remove n
+        if ! grep -q "^nodejs_version:" /etc/yunohost/apps/*/settings.yml; then
+            ynh_safe_rm "$N_PREFIX"
+            sed --in-place "/N_PREFIX/d" /root/.bashrc
+        fi
     fi
 }
diff --git a/helpers/helpers.v2.1.d/ruby b/helpers/helpers.v2.1.d/ruby
--- a/helpers/helpers.v2.1.d/ruby
+++ b/helpers/helpers.v2.1.d/ruby
@@ -18,13 +18,12 @@
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 
-readonly RBENV_ROOT="/opt/rbenv"
-export RBENV_ROOT
+export MISE_RUBY_COMPILE=false
 
 _ynh_load_ruby_in_path_and_other_tweaks() {
 
-    # Get the absolute path of this version of Ruby
-    ruby_dir="$RBENV_ROOT/versions/$app/bin"
+    # Get the absolute path of this version of ruby
+    ruby_dir=$(MISE_DATA_DIR="$MISE_DATA_DIR" MISE_CACHE_DIR="$MISE_CACHE_DIR" MISE_STATE_DIR="$MISE_STATE_DIR" "$MISE_BIN_DIR/mise" bin-paths "ruby@$ruby_version")
 
     if [ ! -e "$ruby_dir" ]; then
         echo "Skipping loading ruby, because it doesn't seem to be provisioned yet. This is likely to happen during restore and other specific contexts."
@@ -35,18 +34,14 @@ _ynh_load_ruby_in_path_and_other_tweaks() {
     if [[ :$PATH: != *":$ruby_dir"* ]]; then
         PATH="$ruby_dir:$PATH"
     fi
+        # Export PATH such that it's available through sudo -E / ynh_exec_as_app
+        export PATH
 
-    # Export PATH such that it's available through sudo -E / ynh_exec_as $app
-    export PATH
-
-    # This is in full lowercase such that it gets replaced in templates
-    path_with_ruby="$PATH"
-    PATH_with_ruby="$PATH"
-
-    # Sets the local application-specific Ruby version
-    pushd "${install_dir}"
-        "$RBENV_ROOT/bin/rbenv" local "$ruby_version"
-    popd
+        # This is in full lowercase such that it gets replaced in templates
+        # shellcheck disable=SC2034
+        path_with_ruby="$PATH"
+        # shellcheck disable=SC2034
+        PATH_with_ruby="$PATH"
 }
 
 # Auto-load Ruby path tweaks if this app uses the ruby resource in the manifest
@@ -54,7 +49,7 @@ if [ -n "${ruby_version:-}" ] && (cat "$YNH_APP_BASEDIR/manifest.toml" | toml_to
     _ynh_load_ruby_in_path_and_other_tweaks
 fi
 
-# Install a specific version of Ruby using rbenv
+# Install a specific version of Ruby using mise
 #
 # The installed version is defined by `$ruby_version` which should be defined as global prior to calling this helper
 #
@@ -63,55 +58,35 @@ fi
 # The helper adds the appropriate, specific version of ruby to the `$PATH` variable (which
 # is preserved when calling ynh_exec_as_app). Also defines:
 #
-# - `$path_with_ruby` to be used in the systemd config (`Environment="PATH=__PATH_WITH_RUBY__"`)
-# - `$ruby_dir`, the directory containing the specific version of ruby, which may be used in the systemd config too (e.g. `ExecStart=__RUBY_DIR__/ruby foo bar`)
+# - `$path_with_ruby` to be used in the systemd config (`Environment="PATH=__PATH_WITH_ruby__"`)
+# - `$ruby_dir`, the directory containing the specific version of ruby, which may be used in the systemd config too (e.g. `ExecStart=__ruby_DIR__/ruby foo bar`)
 ynh_ruby_install() {
 
     [[ -n "${ruby_version:-}" ]] || ynh_die "\$ruby_version should be defined prior to calling ynh_ruby_install"
 
-    # Install or update rbenv
-    _ynh_git_clone "https://github.com/rbenv/rbenv" "${RBENV_ROOT}"
-    _ynh_git_clone "https://github.com/rbenv/ruby-build" "${RBENV_ROOT}/plugins/ruby-build"
-    _ynh_git_clone "https://github.com/tpope/rbenv-aliases" "${RBENV_ROOT}/plugins/rbenv-aliase"
-    _ynh_git_clone "https://github.com/momo-lab/xxenv-latest" "${RBENV_ROOT}/plugins/xxenv-latest"
-
-    mkdir -p "${RBENV_ROOT}/cache"
-    mkdir -p "${RBENV_ROOT}/shims"
-
-    # Install the requested version of Ruby
-    local final_ruby_version=$("${RBENV_ROOT}/bin/rbenv" latest --print "$ruby_version")
+    ynh_mise_install
+    
+    # Install the requested version of ruby
+    local final_ruby_version=$("${MISE_BIN_DIR}"/mise ls-remote ruby@"$ruby_version" --json | jq -r '.[].version' | tail -n1 )
     ruby_version=${final_ruby_version:-$ruby_version}
     ynh_app_setting_set --key=ruby_version --value="$ruby_version"
 
-    for PACKAGE in gcc make libjemalloc-dev libffi-dev libyaml-dev zlib1g-dev; do
-        _ynh_apt_package_is_installed "$PACKAGE" || ynh_die "$PACKAGE is required to install Ruby"
-    done
-
-    echo "Installing Ruby $final_ruby_version"
-    RUBY_CONFIGURE_OPTS="--disable-install-doc --with-jemalloc" MAKE_OPTS="-j2" "${RBENV_ROOT}/bin/rbenv" install --skip-existing "$ruby_version" 2>&1
-
-    # Recreate rbenv alias for this version
-    if "${RBENV_ROOT}/bin/rbenv" alias --list | grep --quiet "$app "; then
-        "${RBENV_ROOT}/bin/rbenv" alias "$app" --remove
-    fi
-    ${RBENV_ROOT}/bin/rbenv alias "$app" "$ruby_version"
-
-    # Cleanup Ruby versions
-    _ynh_ruby_cleanup
+    # Installing precompiled ruby from the $install_dir so the created mise.toml will be at the right place
+    pushd "$install_dir" || ynh_die
+        ynh_hide_warnings env MISE_RUBY_COMPILE=false MISE_DATA_DIR="$MISE_DATA_DIR" MISE_CACHE_DIR="$MISE_CACHE_DIR" MISE_STATE_DIR="$MISE_STATE_DIR" "$MISE_BIN_DIR"/mise use ruby@"$ruby_version"
+    popd || ynh_die
 
     _ynh_load_ruby_in_path_and_other_tweaks
 }
 
-# Remove the version of Ruby used by the app.
+# Remove the version of ruby used by the app.
 #
-# This helper will also cleanup unused Ruby versions
+# This helper will also cleanup unused ruby versions
 #
 # usage: ynh_ruby_remove
 ynh_ruby_remove() {
 
     [[ -n "${ruby_version:-}" ]] || ynh_die "\$ruby_version should be defined prior to calling ynh_ruby_remove"
-
-    "${RBENV_ROOT}/bin/rbenv" alias "$app" --remove
 
     # Remove the line for this app
     ynh_app_setting_delete --key="ruby_version"
@@ -120,29 +95,40 @@ ynh_ruby_remove() {
     _ynh_ruby_cleanup
 }
 
-# Remove no more needed versions of Ruby used by the app.
-#
-# [internal]
-#
-# This helper will check what Ruby version are no more required,
-# and uninstall them
-# If no app uses Ruby, rbenv will be also removed.
 _ynh_ruby_cleanup() {
 
-    # Remove no more needed Ruby versions
-    local installed_ruby_versions=$("${RBENV_ROOT}/bin/rbenv" versions --bare --skip-aliases | grep -Ev '/')
+    # Remove no more needed versions of ruby used by the app.
+    # This helper will check what ruby version are no more required,
+    # and uninstall them
+    local installed_ruby_versions=$(MISE_DATA_DIR="$MISE_DATA_DIR" MISE_CACHE_DIR="$MISE_CACHE_DIR" MISE_STATE_DIR="$MISE_STATE_DIR" "${MISE_BIN_DIR}/mise" ls ruby --json | jq -r '.[].version')
     for installed_ruby_version in $installed_ruby_versions; do
-        if ! grep -qE "^ruby_version: '?$installed_ruby_version'?" /etc/yunohost/apps/*/settings.yml; then
-            ynh_print_info "Removing Ruby-$installed_ruby_version"
-            "$RBENV_ROOT/bin/rbenv" uninstall --force "$installed_ruby_version"
+        if [[ -n "$installed_ruby_version" ]] && ! grep -qE "^ruby_version: '?$installed_ruby_version'?" /etc/yunohost/apps/*/settings.yml; then
+            ynh_print_info "Removing ruby@$installed_ruby_version"
+            ynh_hide_warnings "$MISE_BIN_DIR/mise" unuse ruby@"$installed_ruby_version"
+            ynh_hide_warnings "$MISE_BIN_DIR/mise" uninstall ruby@"$installed_ruby_version"
         fi
     done
 
-    # If no app uses Ruby anymore
-    if ! grep -q "^ruby_version:" /etc/yunohost/apps/*/settings.yml; then
-        # Remove rbenv environment configuration
-        ynh_print_info "Removing rbenv"
-        ynh_safe_rm "$RBENV_ROOT"
-        ynh_safe_rm "/etc/profile.d/rbenv.sh"
+    ## LEGACY but still there until all ruby apps have migrated to mise
+    # Remove no more needed Ruby versions
+    export RBENV_ROOT="/opt/rbenv"
+    
+    if -e "$RBENV_ROOT"; then
+
+        local installed_ruby_versions=$("${RBENV_ROOT}/bin/rbenv" versions --bare --skip-aliases | grep -Ev '/')
+        for installed_ruby_version in $installed_ruby_versions; do
+            if ! grep -qE "^ruby_version: '?$installed_ruby_version'?" /etc/yunohost/apps/*/settings.yml; then
+                ynh_print_info "Removing Ruby-$installed_ruby_version"
+                "$RBENV_ROOT/bin/rbenv" uninstall --force "$installed_ruby_version"
+            fi
+        done
+
+        # If no app uses Ruby anymore
+        if ! grep -q "^ruby_version:" /etc/yunohost/apps/*/settings.yml; then
+            # Remove rbenv environment configuration
+            ynh_print_info "Removing rbenv"
+            ynh_safe_rm "$RBENV_ROOT"
+            ynh_safe_rm "/etc/profile.d/rbenv.sh"
+        fi
     fi
 }
